# What is Numpy?

Single dimensional array

In [2]:
# importing numpy module
import numpy as np
 
# creating list
list = [1, 2, 3, 4]
 
# creating numpy array
sample_array = np.array(list)
 
print("List in python : ", list)
 
print("Numpy Array in python :",sample_array)

List in python :  [1, 2, 3, 4]
Numpy Array in python : [1 2 3 4]


Multi dimensional array

In [3]:
# importing numpy module
import numpy as np
 
# creating list
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]
 
# creating numpy array
sample_array = np.array([list_1,
                         list_2,
                         list_3])
 
print("Numpy multi dimensional array in python\n",
      sample_array)

Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Shape** of an array is the number of elements across each dimension.

In [6]:
print(sample_array.shape)

(3, 4)


**Datatype** of a numpy array

In [7]:
print(sample_array.dtype)

int64


Number of elements of the array using np.size

In [31]:
print(sample_array.size)

12


`np.arange`<br>
Syntax: numpy.arange([start, ]stop, [step, ]dtype=None)


In [15]:
import numpy as np

list2 = np.arange(0,10,5)
print(list2)

[0 5]


``np.linspace``<br>
Syntax: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)



In [14]:
import numpy as np

list2 = np.linspace(0,10,5)
print(list2)

[ 0.   2.5  5.   7.5 10. ]


``np.empty``<br>
Syntax: numpy.empty(shape, dtype=float, order=’C’)

In [21]:
import numpy as np

list2 = np.empty([4,5])
print(list2)

[[0.  0.  0.3 1.  0. ]
 [0.  1.  1.  1.  1. ]
 [1.  1.  1.  0.  0. ]
 [1.  0.5 0.  0.  1. ]]


``np.ones``<br>
Syntax: numpy.ones(shape, dtype=None, order=’C’)

In [22]:
import numpy as np

list2 = np.ones([4,5])
print(list2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


``np.zeros``<br>
Syntax: numpy.zeros(shape, dtype=None, order=’C’)

In [24]:
import numpy as np

list2 = np.zeros([4,5])
print(list2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Sorting using numpy arrays

In [25]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

Concatenating two numpy arrays<br>
`numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")`


In [30]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6 7 8]


# Indexing and slicing

In [35]:
data = np.array([1, 2, 3])
print(data[1])

print(data[0:2])

2
[1 2]


In [53]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

print('')
print(a[a < 5])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[1 2 3 4]


In [54]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [55]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [41]:
c = a[(a > 2) & (a < 11)] #using or, and statments
print(c)

[ 3  4  5  6  7  8  9 10]


In [56]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [69]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a.sum())

78


In [58]:
b = a *2
print(b)

[2 4 6 8]


In [63]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
max_num = a.max()
print(max_num) #can use min() similarly

12


In [67]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print('')
trans_arr = a.transpose()
print(trans_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [50]:
print(np.flip(b))

[8 6 4 2]


In [68]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(x)
print('')
print(x.flatten())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Reference - https://numpy.org/doc/stable/user/absolute_beginners.html